[project]
name = "aws-central-infrastructure"
version = "0.1.0"
description = "Managing the non-management-account Central Infrastructure for an AWS Organization"

readme = "README.md"
requires-python = ">=3.13.1"

dependencies = [
    # Specific to this template


    # Managed by upstream template
    "pyright>=1.1.400",
    "pytest>=8.3.5",
    "pytest-cov>=6.1.1",
    "pytest-randomly>=3.16.0",
    "pulumi>=3.167.0",
    "pulumi-aws>=6.77.0",
    "pulumi-aws-native>=1.27.0",
    "pulumi-command>=1.0.2",
    "ephemeral-pulumi-deploy>=0.0.4",
    "lab-auto-pulumi>=0.1.12",
    "boto3>=1.37.11",
    "boto3-stubs[all]==1.38.21", # there's a bug/conflict in 1.37.4 affecting pyright: https://github.com/LabAutomationAndScreening/copier-cloud-courier-infrastructure/actions/runs/13596390146/job/38014193360#step:11:69
    "pydantic>=2.11.4",
]

[tool.uv]
package = true
